language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install -r requirements.txt
  - chdir tests
install:
  - coverage run -m pytest test_postgres_restorer.py
services: postgresql
after_success:
  - codecov